### ISSUE TITLE
Plugin out of date

### ISSUE THREAD

**Issue by Antbrooksuk** [NativeScript/sample-push-plugin#1]
Plugin not found when installed via Plugins Marketplace.

Looks like plugin is out of date.

**Comment by AntonDobrev** [comment]
The plugin used in this sample is available from:

[Telerik Verified Plugins Marketplace](http://plugins.telerik.com/nativescript/plugin/telerik-push-notifications)

[NPM](https://www.npmjs.com/package/nativescript-push-notifications)
