### ISSUE TITLE
Sample App is confusing

### ISSUE THREAD

**Issue by Daxito** [NativeScript/sample-push-plugin#5]
I dont see the relation between Everlive and nativescript-push-notifications plugin, in the sample app you just require the pushPlugin but never use it.

What is the relation between Everlive and pushPlugin?? which one should I use? I want to use Telerik Backend Services.

Seems like all I need is Everlive only? Because if I just use the pushplugin I dont see how to pass in my App Id..... makes sense?

**Comment by dtopuzov** [comment]
Actually Everlive was the old name of Telerik Backend Services.
